import React from 'react';
import { DISCLAIMER_TEXT } from '../constants/legal';
import { useSEO } from '../hooks/useSEO';
import { ShieldAlert } from 'lucide-react';

export function DisclaimerPage() {
  useSEO({
    title: 'Disclaimer | RuralPredictor',
    description: 'Legal disclaimer and terms of use for RuralPredictor estimates and calculations.',
  });

  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
      <div className="mb-10 flex items-center gap-4">
        <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-orange-100 text-orange-600">
          <ShieldAlert className="h-6 w-6" />
        </div>
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Legal Disclaimer</h1>
          <p className="text-slate-500 mt-1 mb-0">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        </div>
      </div>

      <div className="prose prose-slate max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-[#2d5a27] prose-a:font-medium prose-p:leading-relaxed bg-white p-8 sm:p-12 rounded-3xl border border-slate-200 shadow-sm">
        <h3 className="text-xl font-bold text-slate-800 mb-4 mt-0">General Disclaimer</h3>
        <p className="text-slate-600 mb-8">{DISCLAIMER_TEXT.standard}</p>
        
        <h3 className="text-xl font-bold text-slate-800 mb-4">Tool-Specific Estimates</h3>
        <p className="text-slate-600 mb-8">RuralPredictor provides dynamic forecasting, yield prediction, and cost estimates using historical data and statistical models. These are predictive models and inherently uncertain. They must not be the sole basis for business, operational, or agricultural decisions.</p>

        <h3 className="text-xl font-bold text-slate-800 mb-4">No Professional Advice</h3>
        <p className="text-slate-600 mb-8">Information provided on this subdomain does not constitute financial, legal, engineering, tax, or professional agricultural advice. You are responsible for consulting qualified local professionals or certified advisors before acting upon any projections or model outputs generated by this site.</p>

        <h3 className="text-xl font-bold text-slate-800 mb-4">Limitation of Liability</h3>
        <p className="text-slate-600 mb-8">Under no circumstances shall Rural Ops Tools, its affiliates, partners, or contributors be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with your access or use of or inability to access or use the application and any third party content and services.</p>

        <div className="mt-12 pt-8 border-t border-slate-200">
          <p className="text-sm text-slate-500 leading-relaxed">
            This subdomain is a conceptual prediction hub that is part of the broader <a href="https://ruralopstools.com" target="_blank" rel="noopener noreferrer" className="underline hover:text-[#2d5a27]">Rural Ops Tools</a> ecosystem. Please reference the master site for shared <a href="https://ruralopstools.com/privacy-policy" target="_blank" rel="noopener noreferrer" className="underline hover:text-[#2d5a27]">Privacy Policies</a> and <a href="https://ruralopstools.com/terms-of-use" target="_blank" rel="noopener noreferrer" className="underline hover:text-[#2d5a27]">Terms of Use</a>.
          </p>
        </div>
      </div>
    </div>
  );
}
